/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd;

import ConexionSQL.Conexion;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author paubo
 */
public class AdminSetup extends javax.swing.JDialog {
    
     private Conexion setupAdmin;
    /**
     * Creates new form AdminSetup
     */
    public AdminSetup(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(157,210,228));
    }
    
     public AdminSetup(InicioSesionAdministrador aThis, boolean modal, Conexion inicioSesionAd) throws SQLException {
        super(aThis, modal);
        initComponents();
        setupAdmin = inicioSesionAd;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(157,210,228));
    }
     
     public AdminSetup(RegistroPersona aThis, boolean modal, Conexion registroDatos) throws SQLException {
        super(aThis, modal);
        initComponents();
        setupAdmin = registroDatos;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(157,210,228));
    }

    AdminSetup(RegistrarEvaluaciones aThis, boolean modal, Conexion registrarEvaluaciones) throws SQLException{
        super(aThis, modal);
        initComponents();
        setupAdmin = registrarEvaluaciones;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(157,210,228));
    }

    AdminSetup(RegistrarDireccion aThis, boolean modal, Conexion registrarDireccion) throws SQLException {
        super(aThis, modal);
        initComponents();
        setupAdmin = registrarDireccion;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(157,210,228));
    }

    AdminSetup(RegistrarCursos aThis, boolean modal, Conexion registrarCursos) throws SQLException{
        super(aThis, modal);
        initComponents();
        setupAdmin = registrarCursos;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(157,210,228));
    }

    AdminSetup(ModificarEvaluaciones aThis, boolean modal, Conexion modificarEvaluaciones) throws SQLException{
        super(aThis, modal);
        initComponents();
        setupAdmin = modificarEvaluaciones;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(157,210,228));
    }

    AdminSetup(ModificarDireccion aThis, boolean modal, Conexion modificarDireccion) throws SQLException{
        super(aThis, modal);
        initComponents();
        setupAdmin = modificarDireccion;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(157,210,228));
    }

    AdminSetup(ModificarPersona aThis, boolean modal, Conexion modificarDatos) throws SQLException{
        super(aThis, modal);
        initComponents();
        setupAdmin = modificarDatos;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(157,210,228));
    }

    AdminSetup(ModificarCursos aThis, boolean modal, Conexion modificarCurso) throws SQLException{
        super(aThis, modal);
        initComponents();
        setupAdmin = modificarCurso;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(157,210,228));
    }

    AdminSetup(ConsultarEstadisticas aThis, boolean modal, Conexion consultarEstadisticas) throws SQLException{
        super(aThis, modal);
        initComponents();
        setupAdmin = consultarEstadisticas;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(157,210,228));
    }

    AdminSetup(ConsultasProfesor aThis, boolean modal, Conexion evaluacionDocente) throws SQLException{
        super(aThis, modal);
        initComponents();
        setupAdmin = evaluacionDocente;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(157,210,228));
    }

    AdminSetup(ConsultasEstudiante aThis, boolean modal, Conexion inicioEstudiante) throws SQLException{
        super(aThis, modal);
        initComponents();
        setupAdmin = inicioEstudiante;
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(157,210,228));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonRegistrarPersona = new javax.swing.JButton();
        BotonModificarPersona = new javax.swing.JButton();
        BotonEstadisticas = new javax.swing.JButton();
        BotonEstudiantes = new javax.swing.JButton();
        BotonProfesores = new javax.swing.JButton();
        regresar = new javax.swing.JButton();
        BotonRegistrarCursos = new javax.swing.JButton();
        BotonRegistrarEvaluaciones = new javax.swing.JButton();
        BotonRegistrarDireccion = new javax.swing.JButton();
        BotonModificarCursos = new javax.swing.JButton();
        BotonModificarEvaluaciones = new javax.swing.JButton();
        BotonModificarDireccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        jLabel1.setText("Admin");

        BotonRegistrarPersona.setBackground(new java.awt.Color(255, 193, 5));
        BotonRegistrarPersona.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        BotonRegistrarPersona.setText("Registrar Persona");
        BotonRegistrarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarPersonaActionPerformed(evt);
            }
        });

        BotonModificarPersona.setBackground(new java.awt.Color(255, 193, 5));
        BotonModificarPersona.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        BotonModificarPersona.setText("Modificar Persona");
        BotonModificarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarPersonaActionPerformed(evt);
            }
        });

        BotonEstadisticas.setBackground(new java.awt.Color(255, 193, 5));
        BotonEstadisticas.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        BotonEstadisticas.setText("Consultar Estadisticas");
        BotonEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstadisticasActionPerformed(evt);
            }
        });

        BotonEstudiantes.setBackground(new java.awt.Color(255, 193, 5));
        BotonEstudiantes.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        BotonEstudiantes.setText("Consultas Estudiantes");
        BotonEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstudiantesActionPerformed(evt);
            }
        });

        BotonProfesores.setBackground(new java.awt.Color(255, 193, 5));
        BotonProfesores.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        BotonProfesores.setText("Consultas Profesores");
        BotonProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonProfesoresActionPerformed(evt);
            }
        });

        regresar.setBackground(new java.awt.Color(255, 193, 5));
        regresar.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        BotonRegistrarCursos.setBackground(new java.awt.Color(255, 193, 5));
        BotonRegistrarCursos.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        BotonRegistrarCursos.setText("Registrar Cursos");
        BotonRegistrarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarCursosActionPerformed(evt);
            }
        });

        BotonRegistrarEvaluaciones.setBackground(new java.awt.Color(255, 193, 5));
        BotonRegistrarEvaluaciones.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        BotonRegistrarEvaluaciones.setText("Registrar Evaluaciones");
        BotonRegistrarEvaluaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarEvaluacionesActionPerformed(evt);
            }
        });

        BotonRegistrarDireccion.setBackground(new java.awt.Color(255, 193, 5));
        BotonRegistrarDireccion.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        BotonRegistrarDireccion.setText("Registrar Dirección ");
        BotonRegistrarDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarDireccionActionPerformed(evt);
            }
        });

        BotonModificarCursos.setBackground(new java.awt.Color(255, 193, 5));
        BotonModificarCursos.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        BotonModificarCursos.setText("Modificar Cursos");
        BotonModificarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarCursosActionPerformed(evt);
            }
        });

        BotonModificarEvaluaciones.setBackground(new java.awt.Color(255, 193, 5));
        BotonModificarEvaluaciones.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        BotonModificarEvaluaciones.setText("Modificar Evaluaciones");
        BotonModificarEvaluaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarEvaluacionesActionPerformed(evt);
            }
        });

        BotonModificarDireccion.setBackground(new java.awt.Color(255, 193, 5));
        BotonModificarDireccion.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        BotonModificarDireccion.setText("Modificar Dirección");
        BotonModificarDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarDireccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(BotonRegistrarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(BotonModificarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(BotonEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(BotonRegistrarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(BotonModificarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(BotonEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(BotonRegistrarEvaluaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(BotonModificarEvaluaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(BotonProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(BotonRegistrarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(BotonModificarDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonRegistrarPersona)
                    .addComponent(BotonModificarPersona)
                    .addComponent(BotonEstadisticas))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonRegistrarCursos)
                    .addComponent(BotonModificarCursos)
                    .addComponent(BotonEstudiantes))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonRegistrarEvaluaciones)
                    .addComponent(BotonModificarEvaluaciones)
                    .addComponent(BotonProfesores))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonRegistrarDireccion)
                    .addComponent(BotonModificarDireccion))
                .addGap(245, 245, 245)
                .addComponent(regresar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistrarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarPersonaActionPerformed
       this.dispose();
        RegistroPersona iniRegistroDatos;
         try {
             iniRegistroDatos = new RegistroPersona(this,true,setupAdmin);
             iniRegistroDatos.setVisible(true);
         } catch (SQLException ex) {
             Logger.getLogger(AdminSetup.class.getName()).log(Level.SEVERE, null, ex);
         }
       
    }//GEN-LAST:event_BotonRegistrarPersonaActionPerformed

    private void BotonModificarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarPersonaActionPerformed
        this.dispose();
        ModificarPersona ventanaModificarDatos = null;
         try {
             ventanaModificarDatos = new ModificarPersona(this,true,setupAdmin);
         } catch (SQLException ex) {
             Logger.getLogger(AdminSetup.class.getName()).log(Level.SEVERE, null, ex);
         }
        ventanaModificarDatos.setVisible(true);
    }//GEN-LAST:event_BotonModificarPersonaActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        this.dispose();
        InicioSesionAdministrador ventaAdmin = new InicioSesionAdministrador(this,true,setupAdmin);
        ventaAdmin.setVisible(true);

    }//GEN-LAST:event_regresarActionPerformed

    private void BotonRegistrarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarCursosActionPerformed
        this.dispose();
        RegistrarCursos registrarCursos = null;
         try {
             registrarCursos = new RegistrarCursos(this,true,setupAdmin);
         } catch (SQLException ex) {
             Logger.getLogger(AdminSetup.class.getName()).log(Level.SEVERE, null, ex);
         }
        registrarCursos.setVisible(true);   
    }//GEN-LAST:event_BotonRegistrarCursosActionPerformed

    private void BotonModificarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarCursosActionPerformed
    this.dispose();
        ModificarCursos modificarCursos = null;
         try {
             modificarCursos = new ModificarCursos(this,true,setupAdmin);
         } catch (SQLException ex) {
             Logger.getLogger(AdminSetup.class.getName()).log(Level.SEVERE, null, ex);
         }
    modificarCursos.setVisible(true);      
    }//GEN-LAST:event_BotonModificarCursosActionPerformed

    private void BotonRegistrarEvaluacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarEvaluacionesActionPerformed
        this.dispose();
        RegistrarEvaluaciones registrarEvaluaciones = null;
         try {
             registrarEvaluaciones = new RegistrarEvaluaciones(this,true,setupAdmin);
         } catch (SQLException ex) {
             Logger.getLogger(AdminSetup.class.getName()).log(Level.SEVERE, null, ex);
         }
        registrarEvaluaciones.setVisible(true);         
    }//GEN-LAST:event_BotonRegistrarEvaluacionesActionPerformed

    private void BotonRegistrarDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarDireccionActionPerformed
    this.dispose();
    RegistrarDireccion iniRegistrarDireccion;
    try{
        iniRegistrarDireccion = new RegistrarDireccion(this,true,setupAdmin);
        iniRegistrarDireccion.setVisible(true); 
    }catch (SQLException ex) {
        Logger.getLogger(AdminSetup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonRegistrarDireccionActionPerformed

    private void BotonModificarEvaluacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarEvaluacionesActionPerformed
        this.dispose();
        ModificarEvaluaciones modificarEvaluaciones = null;
         try {
             modificarEvaluaciones = new ModificarEvaluaciones(this,true,setupAdmin);
         } catch (SQLException ex) {
             Logger.getLogger(AdminSetup.class.getName()).log(Level.SEVERE, null, ex);
         }
        modificarEvaluaciones.setVisible(true);       
    }//GEN-LAST:event_BotonModificarEvaluacionesActionPerformed

    private void BotonModificarDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarDireccionActionPerformed
        this.dispose();
        ModificarDireccion modificarDireccion = null;
         try {
             modificarDireccion = new ModificarDireccion(this,true,setupAdmin);
         } catch (SQLException ex) {
             Logger.getLogger(AdminSetup.class.getName()).log(Level.SEVERE, null, ex);
         }
        modificarDireccion.setVisible(true);   
    }//GEN-LAST:event_BotonModificarDireccionActionPerformed

    private void BotonEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstadisticasActionPerformed
        this.dispose();
        ConsultarEstadisticas consultarEstadisticas = new ConsultarEstadisticas(this,true,setupAdmin);
        consultarEstadisticas.setVisible(true);      
    }//GEN-LAST:event_BotonEstadisticasActionPerformed

    private void BotonEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstudiantesActionPerformed
        this.dispose();
        ConsultasEstudiante inicioEstudiante = new ConsultasEstudiante(this,true,setupAdmin);
        inicioEstudiante.setVisible(true);      
    }//GEN-LAST:event_BotonEstudiantesActionPerformed

    private void BotonProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonProfesoresActionPerformed
        this.dispose();
        ConsultasProfesor evaluaciónDocente = new ConsultasProfesor(this,true,setupAdmin);
        evaluaciónDocente.setVisible(true);   
    }//GEN-LAST:event_BotonProfesoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AdminSetup dialog = new AdminSetup(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEstadisticas;
    private javax.swing.JButton BotonEstudiantes;
    private javax.swing.JButton BotonModificarCursos;
    private javax.swing.JButton BotonModificarDireccion;
    private javax.swing.JButton BotonModificarEvaluaciones;
    private javax.swing.JButton BotonModificarPersona;
    private javax.swing.JButton BotonProfesores;
    private javax.swing.JButton BotonRegistrarCursos;
    private javax.swing.JButton BotonRegistrarDireccion;
    private javax.swing.JButton BotonRegistrarEvaluaciones;
    private javax.swing.JButton BotonRegistrarPersona;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
