/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd;

import ConexionSQL.Conexion;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author paubo
 */
public class ConsultasEstudiante extends javax.swing.JDialog {
    private Conexion inicioEstudiante;
        private int idEstudiante;
        ArrayList<String> consultas = new ArrayList();
    /**
     * Creates new form InicioEstudiante
     */
    public ConsultasEstudiante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(new Color(157,210,228));
        botonRegresarAdmin.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    public ConsultasEstudiante(AdminSetup aThis, boolean modal, Conexion setupAdmin) throws SQLException {
       super(aThis, modal);
       initComponents();
       inicioEstudiante = setupAdmin;
       this.getContentPane().setBackground(new Color(157,210,228));
       inicioEstudiante.getCourse(comBoxCurso);
       botonRegresar.setVisible(false);
       inicioEstudiante.getStudent(comBoxEstudiante);
       String NombreProfesor;
        NombreProfesor = (String) comBoxEstudiante.getSelectedItem();
        String[] obteniendoIdProfesor;
        obteniendoIdProfesor = NombreProfesor.split(" ");
        String idProfesora;
        idProfesora = obteniendoIdProfesor[0];
        idEstudiante= Integer.parseInt(idProfesora);
        this.setLocationRelativeTo(null);
    }
    
    public ConsultasEstudiante(InicioEstudiante aThis, boolean modal, Conexion conexion, int id) throws SQLException {
       super(aThis, modal);
       initComponents();
       inicioEstudiante = conexion;
       this.getContentPane().setBackground(new Color(157,210,228));
       inicioEstudiante.getCourse(comBoxCurso);
       botonRegresarAdmin.setVisible(false);
       idEstudiante = id;
       comBoxEstudiante.setVisible(false);
       jLabel7.setVisible(false);
       this.setLocationRelativeTo(null);
    }

    public ConsultasEstudiante(InicioEstudiante aThis, boolean modal, Conexion inicioEstudiante) throws SQLException {
        super(aThis, modal);
       initComponents();
       inicioEstudiante = inicioEstudiante;
       this.getContentPane().setBackground(new Color(157,210,228));
       inicioEstudiante.getCourse(comBoxCurso);
       botonRegresarAdmin.setVisible(false);
       this.setLocationRelativeTo(null);
    }
    
    private void mostrarCursos(int año, int semestre) throws SQLException{
        consultas.clear();
        jTableDatos.clearSelection();
        inicioEstudiante.coursesRegistered(consultas, idEstudiante,semestre, año);
        String matriz [][] = new String[consultas.size()][3];
        int x = 0;
        for (int i = 0; i < consultas.size()/3; i++){
            int columnas = 0;
            for (int j = x; j < x+3; j++){
                matriz[i][columnas] = consultas.get(j);
                columnas++;
            }
            x+=3;
        }
        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
                new String [] {"Curso","Semestre", "Año"}
        ));
    }
    
    private void mostrarEvaluaciones(String curso) throws SQLException{
        consultas.clear();
        jTableDatos.clearSelection();
        inicioEstudiante.noteCourseAndEvaluations(consultas, idEstudiante, curso);
        String matriz [][] = new String[consultas.size()][4];
        int x = 0;
        for (int i = 0; i < consultas.size()/4; i++){
            int columnas = 0;
            for (int j = x; j < x+4; j++){
                matriz[i][columnas] = consultas.get(j);
                columnas++;
            }
            x+=4;
        }
        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
                new String [] {"Curso","Evaluacion", "Nota Evaluacion", "Nota Total"}
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        añoCurso = new javax.swing.JTextField();
        mostrarCursos = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        botonRegresarAdmin = new javax.swing.JButton();
        comBoxSemestre = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDatos = new javax.swing.JTable();
        comBoxCurso = new javax.swing.JComboBox<>();
        mostrarEvaluaciones = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        comBoxEstudiante = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        jLabel1.setText("Estudiante");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel2.setText("Cursos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 95, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel3.setText("Evaluaciones");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(891, 134, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel5.setText("Semestre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 184, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel6.setText("Año");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 142, -1, -1));
        getContentPane().add(añoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 142, 100, -1));

        mostrarCursos.setBackground(new java.awt.Color(255, 193, 5));
        mostrarCursos.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        mostrarCursos.setText("Mostrar");
        mostrarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarCursosActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 180, 100, -1));

        botonRegresar.setBackground(new java.awt.Color(255, 193, 5));
        botonRegresar.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 734, 100, -1));

        botonRegresarAdmin.setBackground(new java.awt.Color(255, 193, 5));
        botonRegresarAdmin.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        botonRegresarAdmin.setText("Regresar");
        botonRegresarAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarAdminActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresarAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 734, 100, -1));

        comBoxSemestre.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        comBoxSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));
        getContentPane().add(comBoxSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 183, 150, -1));

        jLabel4.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel4.setText("Curso");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(759, 184, -1, -1));

        jTableDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 239, 1110, 477));

        comBoxCurso.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        getContentPane().add(comBoxCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(816, 182, 223, -1));

        mostrarEvaluaciones.setBackground(new java.awt.Color(255, 193, 5));
        mostrarEvaluaciones.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        mostrarEvaluaciones.setText("Mostrar");
        mostrarEvaluaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarEvaluacionesActionPerformed(evt);
            }
        });
        getContentPane().add(mostrarEvaluaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(1077, 180, 109, -1));

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setText("Seleccione el estudiante antes de iniciar:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        comBoxEstudiante.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        getContentPane().add(comBoxEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 250, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
    this.dispose();
    InicioEstudiante inicioEstudiante = null;
        try {
            inicioEstudiante = new InicioEstudiante(this,true, inicioEstudiante);
        } catch (SQLException ex) {
            Logger.getLogger(ConsultasEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
    inicioEstudiante.setVisible(true);     
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonRegresarAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarAdminActionPerformed
    this.dispose();
    AdminSetup ventaAdminSetup = null;
        try {
            ventaAdminSetup = new AdminSetup(this,true, inicioEstudiante);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarCursos.class.getName()).log(Level.SEVERE, null, ex);
        }
    ventaAdminSetup.setVisible(true);   
    }//GEN-LAST:event_botonRegresarAdminActionPerformed

    private void mostrarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarCursosActionPerformed
        if(!añoCurso.getText().isEmpty()){
            if(isInt(añoCurso.getText()) && añoCurso.getText().length() == 4){
                String añoString = añoCurso.getText();
                int año = Integer.parseInt(añoString);
                String semestreString = (String) comBoxSemestre.getSelectedItem();
                int semestre = Integer.parseInt(semestreString);
                    try {
                        mostrarCursos(año,semestre);
                    } catch (SQLException ex) {
                        Logger.getLogger(ConsultasEstudiante.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    añoCurso.setText("");
            } else {
                JOptionPane.showMessageDialog(null,"Error! Digite un año valido");
            }
        } else {
            JOptionPane.showMessageDialog(null,"Error! Campo de año vacio");
        }
    }//GEN-LAST:event_mostrarCursosActionPerformed

    private void mostrarEvaluacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarEvaluacionesActionPerformed
       String curso = (String) comBoxCurso.getSelectedItem();
        try {
            mostrarEvaluaciones(curso);
        } catch (SQLException ex) {
            Logger.getLogger(ConsultasEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mostrarEvaluacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultasEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultasEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultasEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultasEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultasEstudiante dialog = new ConsultasEstudiante(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private boolean isInt(String text) {  
        try{
            Integer.parseInt(text);
            return true;
        }
        catch (NumberFormatException nfe){
            return false;
        }  
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField añoCurso;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonRegresarAdmin;
    private javax.swing.JComboBox<String> comBoxCurso;
    private javax.swing.JComboBox<String> comBoxEstudiante;
    private javax.swing.JComboBox<String> comBoxSemestre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDatos;
    private javax.swing.JButton mostrarCursos;
    private javax.swing.JButton mostrarEvaluaciones;
    // End of variables declaration//GEN-END:variables
}
