/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd;

import ConexionSQL.Conexion;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.List;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author paubo
 */
public class ConsultarEstadisticas extends javax.swing.JDialog {
    private Conexion consultarEstadisticas;
    private String CursoSeleccionado;
    private String GeneroSeleccionado;
    /**
     * Creates new form ConsultarEstadisticas
     */
    public ConsultarEstadisticas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(new Color(157,210,228));
    }
    
    public ConsultarEstadisticas(AdminSetup aThis, boolean modal, Conexion setupAdmin) throws SQLException {
        super(aThis, modal);
        initComponents();
        consultarEstadisticas = setupAdmin;
        consultarEstadisticas.getCourseRegistroGrupo(comboBoxCursoCGenero);
        consultarEstadisticas.getCourse(comboBoxCursoMejoresEs);
        consultarEstadisticas.getGender(comboBoxGenero);
        this.getContentPane().setBackground(new Color(157,210,228));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BotonEstudiantesxCursoxGenero = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        RangoTop = new javax.swing.JTextField();
        comboBoxGenero = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BotonTopMejoresEstudiantes = new javax.swing.JButton();
        BotonPromedioNotas = new javax.swing.JButton();
        BotonPorcentajeAbandonos = new javax.swing.JButton();
        BotonEstudiantesRangoEdad = new javax.swing.JButton();
        BotonRegresar = new javax.swing.JButton();
        comboBoxCursoCGenero = new javax.swing.JComboBox<>();
        comboBoxCursoMejoresEs = new javax.swing.JComboBox<>();
        panelGrafico = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        jLabel1.setText("Estadísticas del sistema");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel2.setText("Elija la estadística que desea visualizar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jLabel3.setText("Total de estudiantes por curso por género");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel4.setText("Curso");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 70, -1));

        BotonEstudiantesxCursoxGenero.setBackground(new java.awt.Color(255, 193, 5));
        BotonEstudiantesxCursoxGenero.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        BotonEstudiantesxCursoxGenero.setText("Ver");
        BotonEstudiantesxCursoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstudiantesxCursoxGeneroActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEstudiantesxCursoxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 90, -1));

        jLabel5.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jLabel5.setText("Top de mejores estudiantes");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel6.setText("Curso");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel7.setText("Género");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, -1, -1));

        jLabel8.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel8.setText("Ingrese el rango del top:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 280, -1, -1));

        RangoTop.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        RangoTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RangoTopActionPerformed(evt);
            }
        });
        getContentPane().add(RangoTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 270, 130, 30));

        comboBoxGenero.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        getContentPane().add(comboBoxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, 140, -1));

        jLabel9.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jLabel9.setText("Promedio de notas por curso");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jLabel10.setText("Porcentaje de abandonos de curso");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, -1));

        jLabel11.setFont(new java.awt.Font("Bell MT", 1, 16)); // NOI18N
        jLabel11.setText("Total de estudiantes por rango de edad");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 410, -1, -1));

        BotonTopMejoresEstudiantes.setBackground(new java.awt.Color(255, 193, 5));
        BotonTopMejoresEstudiantes.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        BotonTopMejoresEstudiantes.setText("Ver");
        BotonTopMejoresEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTopMejoresEstudiantesActionPerformed(evt);
            }
        });
        getContentPane().add(BotonTopMejoresEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 320, 90, -1));

        BotonPromedioNotas.setBackground(new java.awt.Color(255, 193, 5));
        BotonPromedioNotas.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        BotonPromedioNotas.setText("Ver");
        BotonPromedioNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPromedioNotasActionPerformed(evt);
            }
        });
        getContentPane().add(BotonPromedioNotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 90, -1));

        BotonPorcentajeAbandonos.setBackground(new java.awt.Color(255, 193, 5));
        BotonPorcentajeAbandonos.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        BotonPorcentajeAbandonos.setText("Ver");
        getContentPane().add(BotonPorcentajeAbandonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 90, -1));

        BotonEstudiantesRangoEdad.setBackground(new java.awt.Color(255, 193, 5));
        BotonEstudiantesRangoEdad.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        BotonEstudiantesRangoEdad.setText("Ver");
        BotonEstudiantesRangoEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEstudiantesRangoEdadActionPerformed(evt);
            }
        });
        getContentPane().add(BotonEstudiantesRangoEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 440, 90, -1));

        BotonRegresar.setBackground(new java.awt.Color(255, 193, 5));
        BotonRegresar.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(BotonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 590, 100, -1));

        comboBoxCursoCGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxCursoCGeneroActionPerformed(evt);
            }
        });
        getContentPane().add(comboBoxCursoCGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 170, 30));

        getContentPane().add(comboBoxCursoMejoresEs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 190, 140, 30));
        getContentPane().add(panelGrafico, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 550, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RangoTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RangoTopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RangoTopActionPerformed

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        this.dispose();
        AdminSetup ventaAdminSetup = null;
        try {
            ventaAdminSetup = new AdminSetup(this, true, consultarEstadisticas);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarCursos.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventaAdminSetup.setVisible(true);
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void BotonEstudiantesxCursoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstudiantesxCursoxGeneroActionPerformed
       String idCurso = (String) comboBoxCursoCGenero.getSelectedItem();
       String[] obteniendoIDCurso = idCurso.split(" ");
       String IDCurso = obteniendoIDCurso[0];
       int IDCURSO = Integer.parseInt(IDCurso);
       
        ArrayList<String> totalStudents = new ArrayList();
        try {
            totalStudents = consultarEstadisticas.totalStudentsCourseGender(IDCURSO);

        } catch (SQLException ex) {
            Logger.getLogger(ConsultarEstadisticas.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultPieDataset datos = new DefaultPieDataset();

        for (int i = 0; i < totalStudents.size(); i++) {
            panelGrafico.removeAll();
            String Primero = totalStudents.get(i).split("=")[0];
            int Segundo = Integer.parseInt(totalStudents.get(i).split("=")[1]);
            datos.setValue(Primero + ": " + Segundo, Segundo);
            
            JFreeChart graficocircular = ChartFactory.createPieChart("Estudiantes por curso por género", datos, true, true, false);
            ChartPanel panel = new ChartPanel(graficocircular);
            panel.setMouseWheelEnabled(true);
            panel.setPreferredSize(new Dimension(550, 420));
            panelGrafico.setLayout(new BorderLayout());
            panelGrafico.add(panel, BorderLayout.NORTH);
            pack();
            panelGrafico.repaint();
        }
    }//GEN-LAST:event_BotonEstudiantesxCursoxGeneroActionPerformed

    private void BotonTopMejoresEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTopMejoresEstudiantesActionPerformed
        ArrayList<String> totalStudents = new ArrayList();
        int top = Integer.parseInt(RangoTop.getText());
        CursoSeleccionado = (String) comboBoxCursoMejoresEs.getSelectedItem();
        GeneroSeleccionado = (String) comboBoxGenero.getSelectedItem();
        try {
            totalStudents = consultarEstadisticas.bestStudentsCourseGender(totalStudents, CursoSeleccionado, GeneroSeleccionado, top);

        } catch (SQLException ex) {
            Logger.getLogger(ConsultarEstadisticas.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultPieDataset datos = new DefaultPieDataset();

        for (int i = 0; i < totalStudents.size(); i++) {
            panelGrafico.removeAll();
            String Primero = totalStudents.get(i).split("=")[0];
            float Segundo = Float.parseFloat(totalStudents.get(i).split("=")[1]);
            datos.setValue(Primero + ": " + Segundo, Segundo);
            
            JFreeChart graficocircular = ChartFactory.createPieChart("Mejores estudiantes por genero y por curso", datos, true, true, false);
            ChartPanel panel = new ChartPanel(graficocircular);
            panel.setMouseWheelEnabled(true);
            panel.setPreferredSize(new Dimension(550, 420));
            panelGrafico.setLayout(new BorderLayout());
            panelGrafico.add(panel, BorderLayout.NORTH);
            pack();
            panelGrafico.repaint();
        }
    }//GEN-LAST:event_BotonTopMejoresEstudiantesActionPerformed

    private void comboBoxCursoCGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxCursoCGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxCursoCGeneroActionPerformed

    private void BotonPromedioNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPromedioNotasActionPerformed
        ArrayList<String> totalStudents = new ArrayList();
        try {
            totalStudents = consultarEstadisticas.notesAverage(totalStudents);

        } catch (SQLException ex) {
            Logger.getLogger(ConsultarEstadisticas.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultPieDataset datos = new DefaultPieDataset();

        for (int i = 0; i < totalStudents.size(); i++) {
            panelGrafico.removeAll();
            String Primero = totalStudents.get(i).split("=")[0];
            float Segundo = Float.parseFloat(totalStudents.get(i).split("=")[1]);
            datos.setValue(Primero + ": " + Segundo, Segundo);
            
            JFreeChart graficocircular = ChartFactory.createPieChart("Promedio de notas por curso", datos, true, true, false);
            ChartPanel panel = new ChartPanel(graficocircular);
            panel.setMouseWheelEnabled(true);
            panel.setPreferredSize(new Dimension(550, 420));
            panelGrafico.setLayout(new BorderLayout());
            panelGrafico.add(panel, BorderLayout.NORTH);
            pack();
            panelGrafico.repaint();
        }
    }//GEN-LAST:event_BotonPromedioNotasActionPerformed

    private void BotonEstudiantesRangoEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEstudiantesRangoEdadActionPerformed
        ArrayList<String> totalStudents = new ArrayList();
        try {
            totalStudents = consultarEstadisticas.totalStudentsRankAge(totalStudents);

        } catch (SQLException ex) {
            Logger.getLogger(ConsultarEstadisticas.class.getName()).log(Level.SEVERE, null, ex);
        }
        DefaultPieDataset datos = new DefaultPieDataset();

        for (int i = 0; i < totalStudents.size(); i++) {
            panelGrafico.removeAll();
            String Primero = totalStudents.get(i).split("=")[0];
            int Segundo = Integer.parseInt(totalStudents.get(i).split("=")[1]);
            datos.setValue(Primero + ": " + Segundo, Segundo);
            
            JFreeChart graficocircular = ChartFactory.createPieChart("Total de estudiantes por rango de edad", datos, true, true, false);
            ChartPanel panel = new ChartPanel(graficocircular);
            panel.setMouseWheelEnabled(true);
            panel.setPreferredSize(new Dimension(550, 420));
            panelGrafico.setLayout(new BorderLayout());
            panelGrafico.add(panel, BorderLayout.NORTH);
            pack();
            panelGrafico.repaint();
        }
    }//GEN-LAST:event_BotonEstudiantesRangoEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarEstadisticas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultarEstadisticas dialog = new ConsultarEstadisticas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEstudiantesRangoEdad;
    private javax.swing.JButton BotonEstudiantesxCursoxGenero;
    private javax.swing.JButton BotonPorcentajeAbandonos;
    private javax.swing.JButton BotonPromedioNotas;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JButton BotonTopMejoresEstudiantes;
    private javax.swing.JTextField RangoTop;
    private javax.swing.JComboBox<String> comboBoxCursoCGenero;
    private javax.swing.JComboBox<String> comboBoxCursoMejoresEs;
    private javax.swing.JComboBox<String> comboBoxGenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panelGrafico;
    // End of variables declaration//GEN-END:variables
}
