package proyectobd;

import ConexionSQL.Conexion;
import java.awt.Color;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author paubo
 */
public class InicioEstudiante extends javax.swing.JDialog {
    private Conexion inicioEstudiante;
    ArrayList<String> consultas = new ArrayList();
    /**
     * Creates new form NewJDialog
     */
    public InicioEstudiante(java.awt.Frame parent, boolean modal) throws SQLException {
        super(parent, modal);
        this.getContentPane().setBackground(new Color(157,210,228));
        inicioEstudiante.getStudent(comBoxEstudiante);
        initComponents();
    }

    InicioEstudiante(MenuInicio aThis, boolean modal, Conexion conexion) throws SQLException {
        super(aThis, modal);
        this.getContentPane().setBackground(new Color(157,210,228));
        initComponents();
        inicioEstudiante.getStudent(comBoxEstudiante);
        inicioEstudiante = conexion;
    }

    InicioEstudiante(ConsultasEstudiante aThis, boolean modal, InicioEstudiante inicioEstudiante) throws SQLException {
        super(aThis, modal);
        this.getContentPane().setBackground(new Color(157,210,228));
        initComponents();
        inicioEstudiante = inicioEstudiante;
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comBoxEstudiante = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        botonReview = new javax.swing.JButton();
        botonConsultas = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        jLabel1.setText("Estudiante");

        comBoxEstudiante.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 18)); // NOI18N
        jLabel7.setText("Seleccione el estudiante: ");

        botonReview.setBackground(new java.awt.Color(255, 193, 5));
        botonReview.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        botonReview.setText("Review");
        botonReview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReviewActionPerformed(evt);
            }
        });

        botonConsultas.setBackground(new java.awt.Color(255, 193, 5));
        botonConsultas.setFont(new java.awt.Font("Bell MT", 0, 24)); // NOI18N
        botonConsultas.setText("Consultas");
        botonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultasActionPerformed(evt);
            }
        });

        botonRegresar.setBackground(new java.awt.Color(255, 193, 5));
        botonRegresar.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(449, 449, 449))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(jLabel7)
                        .addGap(33, 33, 33)
                        .addComponent(comBoxEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(botonReview, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(botonConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comBoxEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonReview, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(243, 243, 243)
                .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonReviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReviewActionPerformed
        Review review = null;
        try {
            review = new Review(this,true,inicioEstudiante);
        } catch (IOException ex) {
            Logger.getLogger(InicioEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(InicioEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
        review.setVisible(true);        
    }//GEN-LAST:event_botonReviewActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
    this.dispose();
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultasActionPerformed
        String NombreProfesor;
        NombreProfesor = (String) comBoxEstudiante.getSelectedItem();
        String[] obteniendoIdProfesor;
        obteniendoIdProfesor = NombreProfesor.split(" ");
        String idProfesor;
        idProfesor = obteniendoIdProfesor[0];
        int idProfesorInt;
        idProfesorInt = Integer.parseInt(idProfesor);
        
        ConsultasEstudiante consultasEstudiante = null;
        try {
            consultasEstudiante = new ConsultasEstudiante(this,true,inicioEstudiante, idProfesorInt);
        } catch (SQLException ex) {
            Logger.getLogger(InicioEstudiante.class.getName()).log(Level.SEVERE, null, ex);
        }
        consultasEstudiante.setVisible(true);  
    }//GEN-LAST:event_botonConsultasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InicioEstudiante dialog = null;
                try {
                    dialog = new InicioEstudiante(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(InicioEstudiante.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultas;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JButton botonReview;
    private javax.swing.JComboBox<String> comBoxEstudiante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
