/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd;

import ConexionSQL.Conexion;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author paubo
 */
public class ModificarDireccion extends javax.swing.JDialog {
    private Conexion modificarDireccion;
    /**
     * Creates new form ModificarDireccion
     */
    public ModificarDireccion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(new Color(157,210,228));
    }
    public ModificarDireccion(AdminSetup aThis, boolean modal, Conexion setupAdmin) throws SQLException {
        super(aThis, modal);
        initComponents();
        modificarDireccion = setupAdmin;
        modificarDireccion.getProvince(comBoxProvincia);
        modificarDireccion.getCanton(comBoxCanton);
        modificarDireccion.getCountry(comBoxPais);
        modificarDireccion.getDistrict(comBoxDistrito);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(157,210,228));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comBoxCanton = new javax.swing.JComboBox<>();
        nombreCanton = new javax.swing.JTextField();
        provinciaCanton = new javax.swing.JTextField();
        botonModificarCanton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        comBoxDistrito = new javax.swing.JComboBox<>();
        nombreDistrito = new javax.swing.JTextField();
        cantonDistrito = new javax.swing.JTextField();
        botonModificarDistrito = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comBoxProvincia = new javax.swing.JComboBox<>();
        nombreProvincia = new javax.swing.JTextField();
        paisProvincia = new javax.swing.JTextField();
        botonModificarProvincia = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        comBoxPais = new javax.swing.JComboBox<>();
        nombrePais = new javax.swing.JTextField();
        botonModificarPais = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        jLabel1.setText("Modificar Direcciones");

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel2.setText("Canton");

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel3.setText("Seleccione el canton a modificar:");

        jLabel4.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel4.setText("Nombre");

        jLabel5.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel5.setText("Id Provincia");

        comBoxCanton.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        nombreCanton.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        provinciaCanton.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        botonModificarCanton.setBackground(new java.awt.Color(255, 193, 5));
        botonModificarCanton.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        botonModificarCanton.setText("Modificar");
        botonModificarCanton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarCantonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel6.setText("Distrito");

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel7.setText("Seleccione el distrito a modificar:");

        jLabel8.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel8.setText("Nombre");

        jLabel9.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel9.setText("Id Canton");

        comBoxDistrito.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        nombreDistrito.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        cantonDistrito.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        botonModificarDistrito.setBackground(new java.awt.Color(255, 193, 5));
        botonModificarDistrito.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        botonModificarDistrito.setText("Modificar");
        botonModificarDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarDistritoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel10.setText("Provincia");

        jLabel11.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel11.setText("Seleccione la provincia a modificar:");

        jLabel12.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel12.setText("Nombre");

        jLabel13.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel13.setText("Id País");

        comBoxProvincia.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        nombreProvincia.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        paisProvincia.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        botonModificarProvincia.setBackground(new java.awt.Color(255, 193, 5));
        botonModificarProvincia.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        botonModificarProvincia.setText("Modificar");
        botonModificarProvincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarProvinciaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel14.setText("País");

        jLabel15.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel15.setText("Seleccione el pais a modificar:");

        jLabel16.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel16.setText("Nombre");

        comBoxPais.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        nombrePais.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        botonModificarPais.setBackground(new java.awt.Color(255, 193, 5));
        botonModificarPais.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        botonModificarPais.setText("Modificar");
        botonModificarPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarPaisActionPerformed(evt);
            }
        });

        botonRegresar.setBackground(new java.awt.Color(255, 193, 5));
        botonRegresar.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 193, 5));
        jButton1.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jButton1.setText("Ver Dtaos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(463, 463, 463)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel2)
                        .addGap(659, 659, 659)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel3)
                        .addGap(73, 73, 73)
                        .addComponent(comBoxCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(295, 295, 295)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(comBoxDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel4)
                        .addGap(233, 233, 233)
                        .addComponent(nombreCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(295, 295, 295)
                        .addComponent(jLabel8)
                        .addGap(180, 180, 180)
                        .addComponent(nombreDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel5)
                        .addGap(206, 206, 206)
                        .addComponent(provinciaCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(295, 295, 295)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cantonDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(botonModificarCanton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(478, 478, 478)
                        .addComponent(botonModificarDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(646, 646, 646)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel11)
                        .addGap(58, 58, 58)
                        .addComponent(comBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(295, 295, 295)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(comBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213)
                        .addComponent(nombreProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(295, 295, 295)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(nombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213)
                        .addComponent(paisProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(529, 529, 529)
                        .addComponent(botonModificarPais, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(botonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(291, 291, 291)
                .addComponent(botonModificarProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comBoxCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(comBoxDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4))
                    .addComponent(nombreCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(nombreDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(provinciaCanton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(cantonDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(botonModificarCanton))
                    .addComponent(botonModificarDistrito))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15)
                            .addComponent(comBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(nombreProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(nombrePais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonModificarPais)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(paisProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonRegresar)
                            .addComponent(jButton1)))
                    .addComponent(botonModificarProvincia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
    this.dispose();
    AdminSetup ventaAdminSetup = null;
        try {
            ventaAdminSetup = new AdminSetup(this,true, modificarDireccion);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    ventaAdminSetup.setVisible(true); 
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonModificarCantonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarCantonActionPerformed
        boolean validandoCantonNombre = false;
        boolean validandoPronvincia = false;
        String Canton = (String) comBoxCanton.getSelectedItem();
        int CantonCode = 0;
        int ProvinceCode = 0;
        try {
            CantonCode = modificarDireccion.getCantonCode(Canton);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
        }
        String NuevoCanton = nombreCanton.getText().toString();
        if(nombreCanton.getText().isEmpty() && provinciaCanton.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"No se ha modificado nada. Campos vacios!");
        } else {
            if(!nombreCanton.getText().isEmpty()){
                try {
                    modificarDireccion.updateCantonName(CantonCode,NuevoCanton);
                    validandoCantonNombre = true;
                } catch (SQLException ex) {
                    Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null,"Error Nombre Canton no modificado!");
                    validandoCantonNombre = false;
                }
            }
            if(!provinciaCanton.getText().isEmpty()){
                try {
                    ProvinceCode = Integer.parseInt(provinciaCanton.getText()); 
                    modificarDireccion.updateCantonProvince(CantonCode,ProvinceCode);
                    validandoPronvincia = true;
                } catch (SQLException ex) {
                    Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null,"Error Provincia Canton no modificado!");
                    validandoPronvincia = false;
                }
            }  
        }
        if(validandoCantonNombre || validandoPronvincia){
            JOptionPane.showMessageDialog(null,"Canton Modificado!!");
            // actualizar combobox
            comBoxCanton.setVisible(false);
            comBoxCanton.removeAllItems();
            try {
                modificarDireccion.getCanton(comBoxCanton);
            } catch (SQLException ex) {
                Logger.getLogger(RegistrarYModificarGenero.class.getName()).log(Level.SEVERE, null, ex);
            }
            comBoxCanton.setVisible(true);
            this.dispose();
            AdminSetup ventaAdminSetup = null;
                try {
                    ventaAdminSetup = new AdminSetup(this,true, modificarDireccion);
                } catch (SQLException ex) {
                    Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
                }
            ventaAdminSetup.setVisible(true); 
        }
    }//GEN-LAST:event_botonModificarCantonActionPerformed

    private void botonModificarProvinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarProvinciaActionPerformed
       boolean validandoProvinciaNombre = false;
        boolean validandoPais = false;
        String Provincia = (String) comBoxProvincia.getSelectedItem();
        int ProvinciaCode = 0;
        int PaisCode = 0;
        try {
            ProvinciaCode = modificarDireccion.getProvinceCode(Provincia);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
        }
            String NuevaProvinciaNombre = nombreProvincia.getText().toString();
        if(nombreProvincia.getText().isEmpty() && paisProvincia.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"No se ha modificado nada. Campos vacios!");
        } else {
            if(!nombreProvincia.getText().isEmpty()){
                try {
                    modificarDireccion.updateProvinceName(ProvinciaCode,NuevaProvinciaNombre);
                    validandoProvinciaNombre = true;
                } catch (SQLException ex) {
                    Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null,"Error Nombre Provincia no modificado!");
                    validandoProvinciaNombre = false;
                }
            }
            if(!paisProvincia.getText().isEmpty()){
                try {
                    PaisCode = Integer.parseInt(paisProvincia.getText());
                    modificarDireccion.updateProvinceCountry(ProvinciaCode,PaisCode);
                    validandoPais = true;
                } catch (SQLException ex) {
                    Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null,"Error País provincia no modificado!");
                    validandoPais = false;
                }
            }  
        }
        if(validandoProvinciaNombre || validandoPais){
            JOptionPane.showMessageDialog(null,"Provincia Modificada!!");
            // actualizar combobox
            comBoxProvincia.setVisible(false);
            comBoxProvincia.removeAllItems();
            try {
                modificarDireccion.getProvince(comBoxProvincia);
            } catch (SQLException ex) {
                Logger.getLogger(RegistrarYModificarGenero.class.getName()).log(Level.SEVERE, null, ex);
            }
            comBoxProvincia.setVisible(true);
            this.dispose();
            AdminSetup ventaAdminSetup = null;
                try {
                    ventaAdminSetup = new AdminSetup(this,true, modificarDireccion);
                } catch (SQLException ex) {
                    Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
                }
            ventaAdminSetup.setVisible(true); 
        }
    }//GEN-LAST:event_botonModificarProvinciaActionPerformed

    private void botonModificarDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarDistritoActionPerformed
        boolean validandoDistritoNombre = false;
        boolean validandoCanton = false;
        String Distrito = (String) comBoxDistrito.getSelectedItem();
        int DistritoCode = 0;
        int CantonCode = 0;
        try {
            DistritoCode = modificarDireccion.getDistrictCode(Distrito);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
        }
            String NuevoNombreDistrito = nombreDistrito.getText().toString();
        if(nombreDistrito.getText().isEmpty() && cantonDistrito.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"No se ha modificado nada. Campos vacios!");
        } else {
            if(!nombreDistrito.getText().isEmpty()){
                try {
                    modificarDireccion.updateDistrictName(DistritoCode,NuevoNombreDistrito);
                    validandoDistritoNombre = true;
                } catch (SQLException ex) {
                    Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null,"Error Nombre Distrito no modificado!");
                    validandoDistritoNombre = false;
                }
            }
            if(!cantonDistrito.getText().isEmpty()){
                try {
                    CantonCode = Integer.parseInt(cantonDistrito.getText());
                    modificarDireccion.updateDistrictCanton(DistritoCode,CantonCode);
                    validandoCanton = true;
                } catch (SQLException ex) {
                    Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null,"Error Canton Distrito no modificado!");
                    validandoCanton = false;
                }
            }  
        }
        if(validandoDistritoNombre || validandoCanton){
            JOptionPane.showMessageDialog(null,"Distrito Modificada!!");
            // actualizar combobox
            comBoxDistrito.setVisible(false);
            comBoxDistrito.removeAllItems();
            try {
                modificarDireccion.getDistrict(comBoxDistrito);
            } catch (SQLException ex) {
                Logger.getLogger(RegistrarYModificarGenero.class.getName()).log(Level.SEVERE, null, ex);
            }
            comBoxDistrito.setVisible(true);
            
            this.dispose();
            AdminSetup ventaAdminSetup = null;
                try {
                    ventaAdminSetup = new AdminSetup(this,true, modificarDireccion);
                } catch (SQLException ex) {
                    Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
                }
            ventaAdminSetup.setVisible(true); 
        }
    }//GEN-LAST:event_botonModificarDistritoActionPerformed

    private void botonModificarPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarPaisActionPerformed

        boolean validandoNombrePais = false;
        String Pais = (String) comBoxDistrito.getSelectedItem();
        int PaisCode = 0;
        String NuevoNombrePais = nombrePais.getText().toString();
        if(nombrePais.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"No se ha modificado nada. Campos vacios!");
        } else {
            try {
                PaisCode = modificarDireccion.getCountryCode(Pais);
            } catch (SQLException ex) {
                Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                modificarDireccion.updateCountryName(PaisCode,NuevoNombrePais);
                validandoNombrePais = true;
            } catch (SQLException ex) {
                Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
                validandoNombrePais = false;
                JOptionPane.showMessageDialog(null,"Error País nombre no modificado!");
            }
        }
        if(validandoNombrePais){
            JOptionPane.showMessageDialog(null,"País modificado!");
            // actualizar combobox
            comBoxPais.setVisible(false);
            comBoxPais.removeAllItems();
            try {
                modificarDireccion.getCountry(comBoxPais);
            } catch (SQLException ex) {
                Logger.getLogger(RegistrarYModificarGenero.class.getName()).log(Level.SEVERE, null, ex);
            }
            comBoxPais.setVisible(true);
            this.dispose();
            AdminSetup ventaAdminSetup = null;
                try {
                    ventaAdminSetup = new AdminSetup(this,true, modificarDireccion);
                } catch (SQLException ex) {
                    Logger.getLogger(ModificarDireccion.class.getName()).log(Level.SEVERE, null, ex);
                }
            ventaAdminSetup.setVisible(true); 
        }
         
    }//GEN-LAST:event_botonModificarPaisActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Tablas tablas = null;
        try {
            tablas = new Tablas(this,true,modificarDireccion);
        } catch (SQLException ex) {
            Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
        tablas.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarDireccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarDireccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarDireccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarDireccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarDireccion dialog = new ModificarDireccion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonModificarCanton;
    private javax.swing.JButton botonModificarDistrito;
    private javax.swing.JButton botonModificarPais;
    private javax.swing.JButton botonModificarProvincia;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JTextField cantonDistrito;
    private javax.swing.JComboBox<String> comBoxCanton;
    private javax.swing.JComboBox<String> comBoxDistrito;
    private javax.swing.JComboBox<String> comBoxPais;
    private javax.swing.JComboBox<String> comBoxProvincia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombreCanton;
    private javax.swing.JTextField nombreDistrito;
    private javax.swing.JTextField nombrePais;
    private javax.swing.JTextField nombreProvincia;
    private javax.swing.JTextField paisProvincia;
    private javax.swing.JTextField provinciaCanton;
    // End of variables declaration//GEN-END:variables
}
