/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd;

import ConexionSQL.Conexion;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author paubo
 */
public class ModificarEvaluaciones extends javax.swing.JDialog {
    private Conexion modificarEvaluaciones;
    /**
     * Creates new form ModificarEvaluaciones
     */
    public ModificarEvaluaciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(new Color(157,210,228));
    }
    
    public ModificarEvaluaciones(AdminSetup aThis, boolean modal, Conexion setupAdmin) throws SQLException {
        super(aThis, modal);
        initComponents();
        modificarEvaluaciones = setupAdmin;
        modificarEvaluaciones.getEvaluation(comboBoxEvaluacion);
        this.getContentPane().setBackground(new Color(157,210,228));
        this.setLocationRelativeTo(null);
        modificarEvaluaciones.getCourseGroup(comBoxGrupoId);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombreEvaluacion = new javax.swing.JTextField();
        descripcionEvaluacion = new javax.swing.JTextField();
        porcentajeEvaluacion = new javax.swing.JTextField();
        cantidadMiemrbros = new javax.swing.JTextField();
        botonFechaEntrega = new javax.swing.JTextField();
        botonModificarEvaluacion = new javax.swing.JButton();
        botonRegresar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        comboBoxEvaluacion = new javax.swing.JComboBox<>();
        botonDatos = new javax.swing.JButton();
        comBoxGrupoId = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        jLabel1.setText("Modificar Evaluaciones");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 18)); // NOI18N
        jLabel2.setText("DD/MM/YYYY");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 420, 160, 20));

        jLabel4.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel4.setText("Nombre");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel5.setText("Descripción");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel6.setText("Porcentaje");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, 20));

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel7.setText("Cantidad de Personas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 310, 160, 40));

        jLabel8.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel8.setText("Fecha de Entrega");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 160, 30));

        nombreEvaluacion.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        nombreEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreEvaluacionActionPerformed(evt);
            }
        });
        getContentPane().add(nombreEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 130, 40));

        descripcionEvaluacion.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        getContentPane().add(descripcionEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 211, 124));

        porcentajeEvaluacion.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        getContentPane().add(porcentajeEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 110, 40));

        cantidadMiemrbros.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        getContentPane().add(cantidadMiemrbros, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 110, 30));

        botonFechaEntrega.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        getContentPane().add(botonFechaEntrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 440, 120, 40));

        botonModificarEvaluacion.setBackground(new java.awt.Color(255, 193, 5));
        botonModificarEvaluacion.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        botonModificarEvaluacion.setText("Modificar");
        botonModificarEvaluacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarEvaluacionActionPerformed(evt);
            }
        });
        getContentPane().add(botonModificarEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 130, 60));

        botonRegresar.setBackground(new java.awt.Color(255, 193, 5));
        botonRegresar.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        botonRegresar.setText("Regresar");
        botonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 630, 101, -1));

        jLabel10.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel10.setText("Grupo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 70, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Llene lo que desea modificar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 290, 30));

        jLabel11.setText("Seleccione la evaluación que desea modificar");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 430, 50));

        getContentPane().add(comboBoxEvaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 230, 50));

        botonDatos.setBackground(new java.awt.Color(255, 193, 5));
        botonDatos.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        botonDatos.setText("Ver Datos");
        botonDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDatosActionPerformed(evt);
            }
        });
        getContentPane().add(botonDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1005, 640, 110, -1));

        getContentPane().add(comBoxGrupoId, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 360, 110, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreEvaluacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreEvaluacionActionPerformed

    private void botonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegresarActionPerformed
    this.dispose();
    AdminSetup ventaAdminSetup = null;
        try {
            ventaAdminSetup = new AdminSetup(this,true, modificarEvaluaciones);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarEvaluaciones.class.getName()).log(Level.SEVERE, null, ex);
        }
    ventaAdminSetup.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_botonRegresarActionPerformed

    private void botonModificarEvaluacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarEvaluacionActionPerformed
       boolean validandoNombre = false;
       boolean validandoDescription = false;
       boolean validandoPorcentaje = false;
       boolean validandoCantMiembros = false;
       boolean validandoNombreCurso = false;
       boolean validandoFormato = false;
       int idGrupo = 0;
       idGrupo =  Integer.parseInt(comBoxGrupoId.getSelectedItem().toString());
       String NombreEvaluacion = (String) comboBoxEvaluacion.getSelectedItem();
       String[] obteniendoIDEvaluacion= NombreEvaluacion.split(" ");
       String ID = obteniendoIDEvaluacion[0];
       int idEvaluacion = Integer.parseInt(ID);
       if(!nombreEvaluacion.getText().isEmpty()){
           try {
               modificarEvaluaciones.updateEvaluationName(idEvaluacion,nombreEvaluacion.getText().toString());
               validandoNombre = true;
           } catch (SQLException ex) {
               Logger.getLogger(ModificarEvaluaciones.class.getName()).log(Level.SEVERE, null, ex);
               validandoNombre = false;
               JOptionPane.showMessageDialog(null,"Nombre no actualizado");
               
           }
       }
       if(!descripcionEvaluacion.getText().isEmpty()){
           try {
               modificarEvaluaciones.updateEvaluationDes(idEvaluacion,descripcionEvaluacion.getText().toString());
               validandoDescription = true;
           } catch (SQLException ex) {
               Logger.getLogger(ModificarEvaluaciones.class.getName()).log(Level.SEVERE, null, ex);
               validandoDescription = false;
               JOptionPane.showMessageDialog(null,"Descripción no actualizada");
           }
       }
       if(!porcentajeEvaluacion.getText().isEmpty()){
           int porcentaje = Integer.parseInt(porcentajeEvaluacion.getText()); 
           try {
               modificarEvaluaciones.updateEvaluationPercentage(idEvaluacion,porcentaje);
               validandoPorcentaje = true;
           } catch (SQLException ex) {
               Logger.getLogger(ModificarEvaluaciones.class.getName()).log(Level.SEVERE, null, ex);
               validandoPorcentaje = false;
               JOptionPane.showMessageDialog(null,"Porcentaje no actualizado");
           }
       }
       if(!cantidadMiemrbros.getText().isEmpty()){
           try {
               modificarEvaluaciones.updateEvaluationMembers(idEvaluacion,cantidadMiemrbros.getText().toString());
               validandoCantMiembros = true;
           } catch (SQLException ex) {
               Logger.getLogger(ModificarEvaluaciones.class.getName()).log(Level.SEVERE, null, ex);
               validandoCantMiembros = false;
               JOptionPane.showMessageDialog(null,"Miemrbros no actualizado");
           }
       }
        try {
            modificarEvaluaciones.updateEvaluationCourseCode(idEvaluacion,idGrupo);
           validandoNombreCurso = true;
        } catch (SQLException ex) {
            Logger.getLogger(ModificarEvaluaciones.class.getName()).log(Level.SEVERE, null, ex);
            validandoNombreCurso = false;
            JOptionPane.showMessageDialog(null,"IdCurso no actualizado!");
       }
       if(!botonFechaEntrega.getText().isEmpty()){
            java.sql.Date DueDateValida = null;

            String DueDate = botonFechaEntrega.getText();
            SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
            Date FechaDate = null;
            try {
                FechaDate = formatoFecha.parse(botonFechaEntrega.getText());
                validandoFormato = true;
             } catch (ParseException ex) {
                //Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null,"Error!\nFormato de fecha incorrecto.");
                validandoFormato = false;
             }
             DueDateValida = new java.sql.Date(FechaDate.getTime());
             if(validandoFormato){
                try {
                    modificarEvaluaciones.updateEvaluationDueDate(idEvaluacion,DueDateValida);
                } catch (SQLException ex) {
                    Logger.getLogger(ModificarEvaluaciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
          }
       if(validandoNombre || validandoDescription || validandoPorcentaje || validandoCantMiembros || validandoNombreCurso || validandoFormato){
           JOptionPane.showMessageDialog(null,"Evaluación modificada!");
            comboBoxEvaluacion.setVisible(false);
            comboBoxEvaluacion.removeAllItems();
            try {
                modificarEvaluaciones.getEvaluation(comboBoxEvaluacion);
            } catch (SQLException ex) {
                 Logger.getLogger(RegistrarYModificarGenero.class.getName()).log(Level.SEVERE, null, ex);
            }
            comboBoxEvaluacion.setVisible(true);
           
           this.dispose();
            AdminSetup ventaAdminSetup = null;
                try {
                    ventaAdminSetup = new AdminSetup(this,true, modificarEvaluaciones);
                } catch (SQLException ex) {
                    Logger.getLogger(ModificarEvaluaciones.class.getName()).log(Level.SEVERE, null, ex);
                }
            ventaAdminSetup.setVisible(true);   
       }
    }//GEN-LAST:event_botonModificarEvaluacionActionPerformed

    private void botonDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDatosActionPerformed
     Tablas tablas = null;
        try {
            tablas = new Tablas(this,true,modificarEvaluaciones);
        } catch (SQLException ex) {
            Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
        tablas.setVisible(true);
    }//GEN-LAST:event_botonDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarEvaluaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarEvaluaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarEvaluaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarEvaluaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarEvaluaciones dialog = new ModificarEvaluaciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDatos;
    private javax.swing.JTextField botonFechaEntrega;
    private javax.swing.JButton botonModificarEvaluacion;
    private javax.swing.JButton botonRegresar;
    private javax.swing.JTextField cantidadMiemrbros;
    private javax.swing.JComboBox<String> comBoxGrupoId;
    private javax.swing.JComboBox<String> comboBoxEvaluacion;
    private javax.swing.JTextField descripcionEvaluacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nombreEvaluacion;
    private javax.swing.JTextField porcentajeEvaluacion;
    // End of variables declaration//GEN-END:variables
}
