/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd;

import ConexionSQL.Conexion;
import java.awt.Color;
import static java.lang.System.out;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author paubo
 */
public class RegistroPersona extends javax.swing.JDialog {

    /**
     * Creates new form RegistroPersona
     */
    private Conexion registroDatos;
    /**
     * Creates new form RegistroDatos
     */
    public RegistroPersona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getContentPane().setBackground(new Color(157,210,228));
        this.getContentPane().setBackground(new Color(157,210,228));
        this.setLocationRelativeTo(null);
        
    }
    public RegistroPersona(AdminSetup aThis, boolean modal, Conexion setupAdmin) throws SQLException {
        super(aThis, modal);
        initComponents();
        registroDatos = setupAdmin;
        this.setLocationRelativeTo(null);
        registroDatos.getDistrict(botonDistrito);
        registroDatos.getGender(botonGenero);
        registroDatos.getPerson(personaTelefono);
        registroDatos.getPerson(personaEmail);
        this.getContentPane().setBackground(new Color(157,210,228));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PrimerNombre = new javax.swing.JTextField();
        SegundoNombre = new javax.swing.JTextField();
        PrimerApellido = new javax.swing.JTextField();
        SegundoApellido = new javax.swing.JTextField();
        FechaNacimiento = new javax.swing.JTextField();
        BotonRegresar = new javax.swing.JButton();
        botonGenero = new javax.swing.JComboBox<>();
        botonCategoria = new javax.swing.JComboBox<>();
        botonDistrito = new javax.swing.JComboBox<>();
        BotonRegistrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        numeroTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tipoTelefono = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        personaTelefono = new javax.swing.JComboBox<>();
        botonRegistrarTelefono = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        direccionEmail = new javax.swing.JTextField();
        personaEmail = new javax.swing.JComboBox<>();
        registrarEmail = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bell MT", 0, 36)); // NOI18N
        jLabel1.setText("Registro de Persona");

        jLabel2.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel2.setText("Primer Nombre");

        jLabel3.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel3.setText("Segundo Nombre");

        jLabel4.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel4.setText("Primer Apellido");

        jLabel6.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel6.setText("Segundo Apellido");

        jLabel7.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel7.setText("Fecha Nacimiento");

        PrimerNombre.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        PrimerNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimerNombreActionPerformed(evt);
            }
        });

        SegundoNombre.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        PrimerApellido.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        SegundoApellido.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        FechaNacimiento.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        BotonRegresar.setBackground(new java.awt.Color(255, 193, 5));
        BotonRegresar.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        BotonRegresar.setText("Regresar");
        BotonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegresarActionPerformed(evt);
            }
        });

        botonGenero.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        botonGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGeneroActionPerformed(evt);
            }
        });

        botonCategoria.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        botonCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Profesor", "Admin" }));

        botonDistrito.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        botonDistrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDistritoActionPerformed(evt);
            }
        });

        BotonRegistrar.setBackground(new java.awt.Color(255, 193, 5));
        BotonRegistrar.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        BotonRegistrar.setText("Registrar");
        BotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarActionPerformed(evt);
            }
        });

        jLabel8.setText("DD/MM/YYYY");

        jLabel9.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel9.setText("Número ");

        numeroTelefono.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel10.setText("Tipo");

        tipoTelefono.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        tipoTelefono.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa ", "Celular", "Oficina" }));

        jLabel11.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel11.setText("Persona");

        personaTelefono.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        botonRegistrarTelefono.setBackground(new java.awt.Color(255, 193, 5));
        botonRegistrarTelefono.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        botonRegistrarTelefono.setText("Registrar");
        botonRegistrarTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarTelefonoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel12.setText("Direccion Email");

        jLabel13.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        jLabel13.setText("Persona");

        direccionEmail.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        personaEmail.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N

        registrarEmail.setBackground(new java.awt.Color(255, 193, 5));
        registrarEmail.setFont(new java.awt.Font("Bell MT", 0, 16)); // NOI18N
        registrarEmail.setText("Registrar");
        registrarEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEmailActionPerformed(evt);
            }
        });

        jLabel14.setText("Registrar Número Persona");

        jLabel15.setText("Registrar Email Persona");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(740, 740, 740)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabel2)
                        .addGap(107, 107, 107)
                        .addComponent(PrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(jLabel9)
                        .addGap(118, 118, 118)
                        .addComponent(numeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel3)
                        .addGap(107, 107, 107)
                        .addComponent(SegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(tipoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel4)
                        .addGap(120, 120, 120)
                        .addComponent(PrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(169, 169, 169)
                        .addComponent(jLabel11)
                        .addGap(74, 74, 74)
                        .addComponent(personaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel7)
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(780, 780, 780)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(640, 640, 640)
                        .addComponent(jLabel12)
                        .addGap(43, 43, 43)
                        .addComponent(direccionEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(420, 420, 420)
                        .addComponent(registrarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(BotonRegresar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(botonGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(botonCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(botonDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jLabel6)
                                .addGap(107, 107, 107)
                                .addComponent(SegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(personaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(botonRegistrarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(PrimerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(numeroTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(SegundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(tipoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(PrimerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(personaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(botonRegistrarTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(SegundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(FechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(botonDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel13))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(personaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(direccionEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(registrarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(BotonRegresar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PrimerNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimerNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrimerNombreActionPerformed

    private void BotonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegresarActionPerformed
        this.dispose();
        AdminSetup ventaAdminSetup = null;
        try {
            ventaAdminSetup = new AdminSetup(this,true,registroDatos);
        } catch (SQLException ex) {
            Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
        ventaAdminSetup.setVisible(true);
    }//GEN-LAST:event_BotonRegresarActionPerformed

    private void botonGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGeneroActionPerformed

    private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
        String Categoria = botonCategoria.getSelectedItem().toString();
        boolean validandoPrimerNombre = false;
        boolean validandoPrimerApellido = false;
        boolean validandoFomatoFecha = false;
        java.sql.Date FechaNacimientoValidada = null;
        
        if(PrimerNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Error: \n El campo Primer Nombre está vacio.");  
         } else {
            validandoPrimerNombre = true;
        }
        // Validando primer apellido no es vacio
        if(PrimerApellido.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Error: \n El campo Primer Apellido está vacio.");  
         } else {
            validandoPrimerApellido = true;
        }
          // //Fecha
        if(FechaNacimiento.getText().isEmpty()){   
            validandoFomatoFecha = true;
        } else {
            String FechaNacimientoRegistro = FechaNacimiento.getText();
            String[] partesFecha = FechaNacimientoRegistro.split("/");
            String ParteDia = partesFecha[0];
            String ParteMes = partesFecha[1];
            String ParteAños = partesFecha[2];
            int parte1int = Integer.parseInt(ParteDia);
            int parte2int = Integer.parseInt(ParteMes);
            int parte3int = Integer.parseInt(ParteAños);
            if(ParteDia.length() != 2 || ParteMes.length() != 2 || ParteAños.length() != 4){
                    JOptionPane.showMessageDialog(null,"Error en Fecha de Nacimiento \nError en el formato.");  
             } else {
                    if(parte1int != 00){
                      if(parte1int > 0 && parte1int <= 31){
                        if(parte2int > 0 && parte2int <= 12){
                           if(parte3int > 1800 && parte3int < 2022){
                             validandoFomatoFecha = true;
                            } else {
                            JOptionPane.showMessageDialog(null,"Error en Fecha de Nacimiento \nEl año debe estar entre 1800 y 2022");
                            validandoFomatoFecha = false;   
                            }
                        } else{
                            JOptionPane.showMessageDialog(null,"Error en Fecha de Nacimiento \n El nes debe estar entre 1 y 12");
                            validandoFomatoFecha = false;
                        }
                    } else {
                        JOptionPane.showMessageDialog(null,"Error en Fecha de Nacimiento \nEl día debe estar entre entre 1 y 31");
                        validandoFomatoFecha = false;}
                    } else {
                    JOptionPane.showMessageDialog(null,"Error en Fecha DE Nacimiento \nDía debe estar entre 1 y 31");
                        validandoFomatoFecha = false;
                    }
                } 
            if(validandoFomatoFecha){
                SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
                Date FechaDate = null;
                try {
                    FechaDate = formatoFecha.parse(FechaNacimiento.getText());
                } catch (ParseException ex) {
                    Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
                }
                FechaNacimientoValidada = new java.sql.Date(FechaDate.getTime());   
            }
        }

         // Distrito
        int Distrito = 0;
        String DistritoNombre = (String) botonDistrito.getSelectedItem();
        try {
            Distrito = registroDatos.getDistrictCode(DistritoNombre);
        } catch (SQLException ex) {
            Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // Genero
        int Genero = 0;
        String GeneroNombre = (String) botonGenero.getSelectedItem();
        try {
            Genero = registroDatos.getGenderCode(GeneroNombre);
        } catch (SQLException ex) {
            Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            if(validandoPrimerNombre && validandoPrimerApellido && validandoFomatoFecha){
                if(registroDatos.addPerson(PrimerNombre.getText(), SegundoNombre.getText(),PrimerApellido.getText(),SegundoApellido.getText(),Genero,Distrito,FechaNacimientoValidada)){
                    int idPersona = registroDatos.getPersonID(PrimerNombre.getText(),SegundoNombre.getText(),PrimerApellido.getText(),SegundoApellido.getText());
                    if(Categoria == "Estudiante"){
                        registroDatos.addStudent(idPersona);    
                    }
                    if(Categoria == "Profesor"){
                          registroDatos.addProfessor(idPersona); 
                    }
                    if(Categoria == "Admin"){
                        String UsuarioAdmin = PrimerNombre.getText() + "Admin";
                        String ContraseñaAdmin = PrimerNombre.getText() + "Password";
                        registroDatos.addAdmin(idPersona,UsuarioAdmin,ContraseñaAdmin);  
                    }
                    JOptionPane.showMessageDialog(null,"Persona Agregada.");
                    this.dispose();
                    AdminSetup ventaAdminSetup = null;
                    ventaAdminSetup = new AdminSetup(this,true,registroDatos);
                    ventaAdminSetup.setVisible(true); 
                    
            } else {
                JOptionPane.showMessageDialog(null,"Persona no agregada.");
            }
         } else {
                JOptionPane.showMessageDialog(null,"Fallo al agregar persona.");
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotonRegistrarActionPerformed

    private void botonDistritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDistritoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonDistritoActionPerformed

    private void registrarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEmailActionPerformed
        boolean validandoCorreo = false;
        String Correo = direccionEmail.getText();
        if(direccionEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Error: \nEl campo Correo esta vacio.");  
        } else {
            int idPersona = 0;
            String NombrePersona = personaEmail.getSelectedItem().toString();
            String[] partesNombre = NombrePersona.split(" ");
            String PrimerNombre = partesNombre[0];
            String SegundoNombre = partesNombre[1];
            String PrimerApellido = partesNombre[2];
            String SegundoApellido = partesNombre[3];
            String Description = tipoTelefono.getSelectedItem().toString();
            try {
               idPersona = registroDatos.getPersonID(PrimerNombre,SegundoNombre,PrimerApellido,SegundoApellido);
            } catch (SQLException ex) {
                Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
            }
            Pattern pattern = Pattern.compile("^[_a-z-A-Z0-9-]+(\\.[_a-z0-9-]+)*@" + 
                "[a-z0-9-]+(\\.[a-z0-9-]+)*(\\.[a-z]{2,4})$");
            Matcher mather = pattern.matcher(direccionEmail.getText().toString());
            if (mather.find()) {
                validandoCorreo = true;
                try {
                    registroDatos.addEmail(Correo,idPersona);
                    validandoCorreo = true;
                } catch (SQLException ex) {
                    Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
                    validandoCorreo = false;
                }
            } else {
                JOptionPane.showMessageDialog(null,"El email inválido."); 
            }
        }
        if(validandoCorreo){
            JOptionPane.showMessageDialog(null,"Email registrado."); 
            this.dispose();
            AdminSetup ventaAdminSetup = null;
            try {
                ventaAdminSetup = new AdminSetup(this,true,registroDatos);
            } catch (SQLException ex) {
                Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
            }
            ventaAdminSetup.setVisible(true); 
        }
  
        
    }//GEN-LAST:event_registrarEmailActionPerformed

    private void botonRegistrarTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarTelefonoActionPerformed
       boolean validandoTelefono = false;
       String telefono;
       int TelefonoNumero = 0;
       int idPersona = 0;
       String NombrePersona = personaTelefono.getSelectedItem().toString();
       String[] partesNombre = NombrePersona.split(" ");
       String PrimerNombre = partesNombre[0];
       String SegundoNombre = partesNombre[1];
       String PrimerApellido = partesNombre[2];
       String SegundoApellido = partesNombre[3];
       String Description = tipoTelefono.getSelectedItem().toString();
        if(numeroTelefono.getText().isEmpty()){
           JOptionPane.showMessageDialog(null,"Teléfono no agregado. Campo Vacio");
       } else {
           TelefonoNumero = Integer.parseInt(numeroTelefono.getText().toString());
           telefono = numeroTelefono.getText().toString();
           
           try {
               idPersona = registroDatos.getPersonID(PrimerNombre,SegundoNombre,PrimerApellido,SegundoApellido);
           } catch (SQLException ex) {
               Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
           }
           try {
               registroDatos.addPhoneNumber(Description,telefono,idPersona);
               validandoTelefono = true;
           } catch (SQLException ex) {
               Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
               validandoTelefono = false;
           }
       }
        if(validandoTelefono){
            JOptionPane.showMessageDialog(null,"Telefono Registrado!");
            this.dispose();
            AdminSetup ventaAdminSetup = null;
           try {
               ventaAdminSetup = new AdminSetup(this,true,registroDatos);
           } catch (SQLException ex) {
               Logger.getLogger(RegistroPersona.class.getName()).log(Level.SEVERE, null, ex);
           }
            ventaAdminSetup.setVisible(true); 
            
        }
    }//GEN-LAST:event_botonRegistrarTelefonoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistroPersona dialog = new RegistroPersona(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JButton BotonRegresar;
    private javax.swing.JTextField FechaNacimiento;
    private javax.swing.JTextField PrimerApellido;
    private javax.swing.JTextField PrimerNombre;
    private javax.swing.JTextField SegundoApellido;
    private javax.swing.JTextField SegundoNombre;
    private javax.swing.JComboBox<String> botonCategoria;
    private javax.swing.JComboBox<String> botonDistrito;
    private javax.swing.JComboBox<String> botonGenero;
    private javax.swing.JButton botonRegistrarTelefono;
    private javax.swing.JTextField direccionEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField numeroTelefono;
    private javax.swing.JComboBox<String> personaEmail;
    private javax.swing.JComboBox<String> personaTelefono;
    private javax.swing.JButton registrarEmail;
    private javax.swing.JComboBox<String> tipoTelefono;
    // End of variables declaration//GEN-END:variables
}
